### ISSUE TITLE
Duplicate games in the game list

### ISSUE THREAD

**Issue by JeromeA** [zond/dipact#209] opened 2021-02-27 16:24 UTC
After entering my move, I clicked [X], and was presented with a game list where "Cold war" and "Simple 2-player game" games appear twice:
![image](https://user-images.githubusercontent.com/168076/109393155-24e38a80-7918-11eb-862a-2fa47c02d42d.png)

When reloading the page, everything went back to normal.

**Comment by JorenC** [comment] 2021-02-27 19:46
@zond I'm not sure when you have time, but I think this issue is because the list needs to have a wrapper around it with a max-width of ...940(?) pixels. That way, when the screen becomes very wide, it will not seek the edges. 

This should be a bug, because when I created this I made it so the desktop wrapper would limit the size (it would be a box in the middle). It might have gotten lost somewhere.  Maybe I have time to fix it...

**Comment by JorenC** [comment] 2021-02-27 19:53
Note that I'm talking about the full-width menu. It should be more like this: (this is with max-width 940px and margin-left/right: auto (in inspector)
![image](https://user-images.githubusercontent.com/7293081/109398539-cc26e880-793d-11eb-899e-f76afb3af7cb.png)

**Comment by zond** [comment] 2021-03-01 12:03
Created #212 to track the width of the lists

**Comment by zond** [comment] 2021-03-01 12:06
@JeromeA I'm unable to reproduce this. Do you have instructions that always work for you?

**Comment by zond** [comment] 2021-03-01 13:48
This seems to happen when games resolve. Maybe push of phase message rriggers it?

**Comment by zond** [comment] 2021-04-13 19:03
This seems to be fixed now, I was unable to repro.

**Closed by zond** 2021-04-13 19:03 UTC
